project:
  type: website

website:
  title: "Internship_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: data_exploration.qmd
        text: Data Exploration

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 5

editor: visual

